### PR TITLE
Use yaml filter in Jinja

### PR DESCRIPTION
**Pull request by thewilkybarkid**
Hopefully addresses https://github.com/elifesciences/journal/pull/806#discussion_r157982923.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
This part is very tricky

**Comment by giorgiosironi** [comment]
Sample generated in Vagrant: https://gist.github.com/anonymous/61158121caf72df387d757ed02fcbac9

**Comment by lsh-0** [comment]
failure on `pr-fresh-variant-critical-css`

```
[34.229.146.98] out: ----------
[34.229.146.98] out:           ID: generate-critical-css
[34.229.146.98] out:     Function: cmd.run
[34.229.146.98] out:         Name: node_modules/.bin/gulp critical-css:generate
[34.229.146.98] out:       Result: False
[34.229.146.98] out:      Comment: Command "node_modules/.bin/gulp critical-css:generate" run
[34.229.146.98] out:      Started: 11:24:28.964963
[34.229.146.98] out:     Duration: 3377.53 ms
[34.229.146.98] out:      Changes:   
[34.229.146.98] out:               ----------
[34.229.146.98] out:               pid:
[34.229.146.98] out:                   9368
[34.229.146.98] out:               retcode:
[34.229.146.98] out:                   1
[34.229.146.98] out:               stderr:
[34.229.146.98] out:                   Chromium unexpecedly not opened - crashed? 
[34.229.146.98] out:                   _browserPagesOpen: 1
[34.229.146.98] out:                   url: http://localhost:8080/resources
[34.229.146.98] out:                   astRules: 1402
[34.229.146.98] out:                   Chromium unexpecedly not opened - crashed? 
[34.229.146.98] out:                   _browserPagesOpen: 1
[34.229.146.98] out:                   url: http://localhost:8080/resources
[34.229.146.98] out:                   astRules: 1431
[34.229.146.98] out:               stdout:
[34.229.146.98] out:                   [11:24:30] Using gulpfile /srv/journal/gulpfile.js
[34.229.146.98] out:                   [11:24:30] Starting 'critical-css:clean'...
[34.229.146.98] out:                   [11:24:30] Finished 'critical-css:clean' after 7.09 ms
[34.229.146.98] out:                   [11:24:30] Starting 'critical-css:generate'...
[34.229.146.98] out:                   restarting chrome after crash
[34.229.146.98] out:                   [11:24:32] 'critical-css:generate' errored after 1.48 s
[34.229.146.98] out:                   [11:24:32] TypeError: node.children.each is not a function
[34.229.146.98] out:                       at Object.eval [as StyleSheet] (eval at createWalker (/srv/journal/node_modules/css-tree/lib/walker/create.js:235:29), <anonymous>:5:15)
[34.229.146.98] out:                       at walk (/srv/journal/node_modules/css-tree/lib/walker/create.js:269:39)
[34.229.146.98] out:                       at walkUp (/srv/journal/node_modules/css-tree/lib/walker/create.js:276:13)
[34.229.146.98] out:                       at Object.toPlainObject (/srv/journal/node_modules/css-tree/lib/convertor/create.js:18:13)
[34.229.146.98] out:                       at /srv/journal/node_modules/penthouse/lib/index.js:169:38
[34.229.146.98] out:                       at next (native)
[34.229.146.98] out:                       at step (/srv/journal/node_modules/penthouse/lib/index.js:45:191)
[34.229.146.98] out:                       at /srv/journal/node_modules/penthouse/lib/index.js:45:437
[34.229.146.98] out:                       at /srv/journal/node_modules/penthouse/lib/index.js:45:99
[34.229.146.98] out:                       at generateCriticalCssWrapped (/srv/journal/node_modules/penthouse/lib/index.js:267:18)
[34.229.146.98] out:                       at /srv/journal/node_modules/penthouse/lib/index.js:236:21
[34.229.146.98] out:                       at next (native)
[34.229.146.98] out:                       at step (/srv/journal/node_modules/penthouse/lib/index.js:45:191)
[34.229.146.98] out:                       at /srv/journal/node_modules/penthouse/lib/index.js:45:361
[34.229.146.98] out:                       at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by thewilkybarkid** [comment]
`pr-fresh-variant-critical-css` is a known problem that I've not been able to recreate anywhere else yet.

**Pull request merged**
