### PR TITLE
Remove feature_digest_channel

### PR DESCRIPTION
**Pull request by thewilkybarkid**
https://github.com/elifesciences/journal/pull/1086 has just been merged.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
This build uses the `master` branch, was it run too soon?
```
[34.228.168.208] out:                   In ParameterBag.php line 102:
[34.228.168.208] out:                                                                                                  
[34.228.168.208] out:                     The service "elife.journal.security.voter.feature.digest_channel" has a dep  
[34.228.168.208] out:                     endency on a non-existent parameter "feature_digest_channel".
```

**Comment by giorgiosironi** [comment]
(answer: yes)

**Comment by thewilkybarkid** [comment]
Hmm, repeated failures.

**Comment by giorgiosironi** [comment]
Smoke tests seem to fail also in the base version which uses the formula's `master`:
```
[54.80.87.241] out:                 <span class="check__name"> </span>                </li>
[54.80.87.241] out: There is not even one status check
[54.80.87.241] out: Script failure, retrying
[54.80.87.241] out: Giving up after 2 consecutive failures
[54.80.87.241] out: Exit code of /usr/local/bin/smoke-tests: 2
```

**Comment by giorgiosironi** [comment]
Using `bldr masterless.launch:journal,pr-84-base-manual,standalone` to check.

**Comment by giorgiosironi** [comment]
Can reproduce with `elife@pr-84-base-manual--journal:/srv/journal$ ./smoke_tests.sh` in there.

Indeed https://pr-84-base-manual--journal.elifesciences.org/status is empty, probably configured to be. It should have `api-dummy` in it? There is definitely something like that returning data e.g. in https://pr-84-base-manual--journal.elifesciences.org/

**Comment by thewilkybarkid** [comment]
That looks like the live API.

**Comment by giorgiosironi** [comment]
I think the defaults from https://github.com/elifesciences/builder-private/commit/4d666d2d9b7c4506fdfe531cc820ad1df81a1e51 (pointing to https://github.com/elifesciences/builder-configuration/blob/master/pillar/journal-pr-public.sls) are creeping in, they were meant for PRs on `journal` but they are being applied to PRs on `journal-formula` too. Not sure how it was working before, but since in this case it's talking to the live API, I will add status checks there as well.

**Comment by giorgiosironi** [comment]
(before the change: it was probably defaulting to `ci` rather than `continuumtest` as an environment)

**Pull request merged**
