### PR TITLE
ELPP-3223 Full package list needed for Chrome headless

### PR DESCRIPTION
**Pull request by giorgiosironi**
#34 still fails on end2end (can't reproduce by mimicking end2end in vagrant).

### CODE REVIEW

**Comment by giorgiosironi** [comment]
This isn't really running the critical-css stuff as it's not in the `example.top`. Therefore https://github.com/elifesciences/elife-jenkins-workflow-libs/commit/195803895e2175786737f5caa6d2e1dcec7be8bd adds the testing of variants, I'll rerun this.

**Comment by giorgiosironi** [comment]
It's an experimental build so I don't know if the additional variant will run correctly, but it will take a while.

**Comment by thewilkybarkid** [comment]
Hmm, is this a difference between fresh instances and existing ones? 😞

(Technically the list is correct, but we're not normally so explicit about dependencies.)

Maybe we should test running `node_modules/.bin/gulp critical-css:generate` in CI?

**Comment by giorgiosironi** [comment]
Would mean the current `end2end` has some missing packages :thinking:  I'll check what is its state, given it is the odd one out (and `prod` could be too).

**Comment by giorgiosironi** [comment]
Analysis: some of these packages are brought in by `firefox` so they do not usually need to be explicitly added in `dev`. They do in `end2end` and `prod` however, as the Selenium setup is not there.

**Pull request merged**
