### PR TITLE
robots.txt, adds /search to disallowed paths for bingbot

### PR DESCRIPTION
**Pull request by lsh-0**
they did 16.2k requests across 4 ips to /search in less than 12 hours

### CODE REVIEW

**Comment by lsh-0** [comment]
> (Assuming Bing doesn't have the same problem Google does.)

Could you remind what the google problem was again?

> (Can we also have a nicer format? One-line is difficult to read.)

I'll look into it

**Comment by lsh-0** [comment]
> (Can we also have a nicer format? One-line is difficult to read.)

can't, actually. It's possible to split a string over multiple lines but unsupported and the behaviour is deprecated.

I could push robots.txt into it's own file, but then these become tricky:

```
map $http_x_forwarded_host $robots_disallow {
    default "/";
    "~^(?<first_host>(?:[^,]+\.)?elifesciences\.org)\s*(?:,|$)" "";
}

location /robots.txt {
    add_header Content-Type text/plain;
    return 200 "User-Agent: *\nDisallow: $robots_disallow\n(...)";
}
```

which I'm not 100% sure is doing, but may be setting the contents of robots.txt dynamically for elife bots?

**Comment by thewilkybarkid** [comment]
> Could you remind what the google problem was again?

Blocking it entirely means it doesn't see the `noindex` directive, and so might still end up being indexed (can be picked up through links).

> It's possible to split a string over multiple lines but unsupported and the behaviour is deprecated

Anything in Jinja that could help?

> but may be setting the contents of robots.txt dynamically for elife bots?

Bit of a special case: https://github.com/elifesciences/journal-formula/pull/79

**Comment by lsh-0** [comment]
> Anything in Jinja that could help?

I got caught up in nginx minutia I forgot about the salt-level stuff. I'll see if I can't push this into project config where it belongs.

> Bit of a special case: #79

this is good to know. I'll add a reference in the config explaining what is going on

**Comment by lsh-0** [comment]
new changes give us something like this:

```bash
$ curl localhost/robots.txt
User-Agent: *
Disallow: /
Disallow: /download/

User-agent: Amazonbot
Disallow: /search/

User-agent: turnitinbot
Disallow: /search/

User-agent: bingbot
Disallow: /search/
```

I'll open PRs for builder-configuration/builder-private

**Comment by lsh-0** [comment]
builder-config changes merged, kicking build

**Comment by lsh-0** [comment]
all green - feel free to merge or I'll do it Monday

**Comment by lsh-0** [comment]
looks like this got overlooked. I'll merge if green

**Pull request merged**
