### PR TITLE
Add redirects to michael eisen’s press package

### PR DESCRIPTION
**Pull request by nlisgo**
Improves: https://github.com/elifesciences/issues/issues/4796

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Looks like a curl PPA is going up and down:
```
[2019-03-15T10:31:38.239Z] [3.84.114.75] out:           ID: curl-7-36-ppa
[2019-03-15T10:31:38.239Z] [3.84.114.75] out:     Function: pkgrepo.managed
[2019-03-15T10:31:38.239Z] [3.84.114.75] out:         Name: deb http://ppa.launchpad.net/costamagnagianfranco/ettercap-stable-backports/ubuntu trusty main
[2019-03-15T10:31:38.239Z] [3.84.114.75] out:       Result: False
[2019-03-15T10:31:38.239Z] [3.84.114.75] out:      Comment: Failed to configure repo 'deb http://ppa.launchpad.net/costamagnagianfranco/ettercap-stable-backports/ubuntu trusty main': Error: key retrieval failed: Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.1CDS7bXezP --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/fkrull-deadsnakes-python2_7.gpg --keyserver keyserver.ubuntu.com --logger-fd 1 --recv-keys 3C2A1859
[2019-03-15T10:31:38.239Z] [3.84.114.75] out:               gpgkeys: key 3C2A1859 can't be retrieved
[2019-03-15T10:31:38.239Z] [3.84.114.75] out:               gpg: requesting key 3C2A1859 from hkp server keyserver.ubuntu.com
[2019-03-15T10:31:38.239Z] [3.84.114.75] out:               gpg: no valid OpenPGP data found.
[2019-03-15T10:31:38.239Z] [3.84.114.75] out:               gpg: Total number processed: 0
[2019-03-15T10:31:38.239Z] [3.84.114.75] out:      Started: 10:28:17.450896
[2019-03-15T10:31:38.239Z] [3.84.114.75] out:     Duration: 7302.782 ms
[2019-03-15T10:31:38.239Z] [3.84.114.75] out:      Changes:   
```

**Comment by giorgiosironi** [comment]
http://keyserver.ubuntu.com/pks/lookup?search=0x3C2A1859&op=vindex seems there and not expired, so I'll re-run the build.

**Comment by giorgiosironi** [comment]
Can't get this to work, we'll check on Monday.

**Comment by thewilkybarkid** [comment]
Rerunning again.

**Comment by thewilkybarkid** [comment]
Just some API status check failures... but all of them?

**Comment by giorgiosironi** [comment]
It's on `base`, too, indicating a problem not on this branch but on `master`.

Maybe not related, but causes an error before:
```
[2019-03-18T08:13:24.346Z] [54.91.92.251] out:           ID: curl-7-36-ppa
[2019-03-18T08:13:24.346Z] [54.91.92.251] out:     Function: pkgrepo.managed
[2019-03-18T08:13:24.346Z] [54.91.92.251] out:         Name: deb http://ppa.launchpad.net/costamagnagianfranco/ettercap-stable-backports/ubuntu trusty main
[2019-03-18T08:13:24.346Z] [54.91.92.251] out:       Result: True
[2019-03-18T08:13:24.346Z] [54.91.92.251] out:      Comment: Configured package repo 'deb http://ppa.launchpad.net/costamagnagianfranco/ettercap-stable-backports/ubuntu trusty main'
[2019-03-18T08:13:24.346Z] [54.91.92.251] out:      Started: 08:09:37.080621
[2019-03-18T08:13:24.346Z] [54.91.92.251] out:     Duration: 4432.037 ms
[2019-03-18T08:13:24.346Z] [54.91.92.251] out:      Changes:   
[2019-03-18T08:13:24.346Z] [54.91.92.251] out:               ----------
[2019-03-18T08:13:24.346Z] [54.91.92.251] out:               repo:
[2019-03-18T08:13:24.346Z] [54.91.92.251] out:                   deb http://ppa.launchpad.net/costamagnagianfranco/ettercap-stable-backports/ubuntu trusty main
[2019-03-18T08:13:24.346Z] [54.91.92.251] out: ----------
[2019-03-18T08:13:24.346Z] [54.91.92.251] out:           ID: curl-7-36-packages
[2019-03-18T08:13:24.346Z] [54.91.92.251] out:     Function: pkg.installed
[2019-03-18T08:13:24.346Z] [54.91.92.251] out:       Result: True
[2019-03-18T08:13:24.346Z] [54.91.92.251] out:      Comment: All specified packages are already installed
[2019-03-18T08:13:24.346Z] [54.91.92.251] out:      Started: 08:09:41.514436
[2019-03-18T08:13:24.347Z] [54.91.92.251] out:     Duration: 95.627 ms
[2019-03-18T08:13:24.347Z] [54.91.92.251] out:      Changes: 
```
curl 7.36 is in the main repository?

**Comment by giorgiosironi** [comment]
Launching `journal--pr-89-base-manual` for a manual test.

**Comment by giorgiosironi** [comment]
Can't reproduce, may be a race condition then.
Some errors say:
```
cURL error 28: Resolving timed out after 1005 milliseconds
```
but the hostname is a local one (set with the `hostname` command even).

**Comment by giorgiosironi** [comment]
Reproduced with
```
bldr masterless.launch:journal,pr-89-base-manual,standalone && bldr cmd:journal--pr-89-base-manual,smoke-tests /srv/journal
```

**Comment by giorgiosironi** [comment]
Sample:
```
{
  "extra": [],
  "datetime": {
    "timezone": "UTC",
    "timezone_type": 3,
    "date": "2019-03-18 10:50:35.395741"
  },
  "channel": "app",
  "level_name": "CRITICAL",
  "level": 500,
  "context": {
    "exception": {
      "trace": [
        "/srv/journal/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:150",
        "/srv/journal/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:103",
        "/srv/journal/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:179",
        "/srv/journal/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:108",
        "/srv/journal/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:123",
        "/srv/journal/vendor/guzzlehttp/promises/src/Promise.php:246",
        "/srv/journal/vendor/guzzlehttp/promises/src/Promise.php:223",
        "/srv/journal/vendor/guzzlehttp/promises/src/Promise.php:267",
        "/srv/journal/vendor/guzzlehttp/promises/src/Promise.php:225",
        "/srv/journal/vendor/guzzlehttp/promises/src/Promise.php:62",
        "/srv/journal/vendor/guzzlehttp/promises/src/EachPromise.php:101",
        "/srv/journal/vendor/guzzlehttp/promises/src/Promise.php:246",
        "/srv/journal/vendor/guzzlehttp/promises/src/Promise.php:223",
        "/srv/journal/vendor/guzzlehttp/promises/src/Promise.php:267",
        "/srv/journal/vendor/guzzlehttp/promises/src/Promise.php:225",
        "/srv/journal/vendor/guzzlehttp/promises/src/Promise.php:62",
        "/srv/journal/src/Controller/StatusController.php:29",
        "/srv/journal/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151",
        "/srv/journal/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68",
        "/srv/journal/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200",
        "/srv/journal/src/AppKernel.php:114",
        "/srv/journal/web/app.php:39"
      ],
      "file": "/srv/journal/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186",
      "code": 0,
      "message": "cURL error 28: Resolving timed out after 1000 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)",
      "class": "GuzzleHttp\\Exception\\ConnectException"
    }
  },
  "message": "Annotations status check failed"
}
```
The first of these should be the DNS that doesn't resolve in time:
```
elife@pr-89-base-manual--journal:~$ grep api_url -A 1 /srv/journal/app/config/parameters.yml
    api_url:
        http://prod--gateway.elife.internal
--
    api_url_public:
        https://api.elifesciences.org
```

**Comment by giorgiosironi** [comment]
There is a retry in place, but both attempts fail with slightly different errors:
```
[3.91.151.184] out:                 <span class="check__name">✘ Annotations</span><span class="check__message">cURL error 28: Connection timed out after 1006 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)</span>                </li>
```
vs.
```
[3.91.151.184] out:                 <span class="check__name">✘ Annotations</span><span class="check__message">cURL error 28: Resolving timed out after 1000 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)</span>                </li>
```

**Comment by giorgiosironi** [comment]
`CURLE_OPERATION_TIMEDOUT (28)` is generic: `Operation timeout. The specified time-out period was reached according to the conditions.`

**Pull request merged**
