### PR TITLE
Add calls_to_action parameter

### PR DESCRIPTION
**Pull request by giorgiosironi**
For https://github.com/elifesciences/issues/issues/4769

Depends on https://github.com/elifesciences/builder-configuration/pull/36

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Extract from Vagrant test:
```
...
    feature_xpub:
        false
    
    calls_to_action:
        []
...
```

**Comment by giorgiosironi** [comment]
Will have to wait on the `builder-configuration` to be in place to run a correct build.

**Comment by thewilkybarkid** [comment]
Maybe add an empty list there now?

**Comment by giorgiosironi** [comment]
Reasonable to test this in time.

**Pull request merged**
