### PR TITLE
Add xPub configuration

### PR DESCRIPTION
**Pull request by thewilkybarkid**
Required by https://github.com/elifesciences/journal/pull/1073.

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
Will need adding to `builder-private` @giorgiosironi. `xpub_client_id` and `xpub_client_secret` will need to match the value in xPub, presume this doesn't exist yet @diversemix @tamlyn?

**Comment by giorgiosironi** [comment]
See https://github.com/elifesciences/builder-configuration/pull/5 for `submit_url`.

**Comment by thewilkybarkid** [comment]
> still missing the feature flag, will be done after these two

Should be in https://github.com/elifesciences/builder-private/pull/248?

**Comment by giorgiosironi** [comment]
It will be, just merging existing PRs before adding it to avoid conflicts.

**Comment by giorgiosironi** [comment]
I am adding xpub-side configuration, but there is already a default value for the `feature_xpub` flag so this can be merged safely.

**Pull request merged**
