### PR TITLE
Add smoke test for critical css

### PR DESCRIPTION
**Pull request by giorgiosironi**
Builds on https://github.com/elifesciences/journal/pull/803

### CODE REVIEW

**Comment by giorgiosironi** [comment]
build hanging:
```
 1447 ?        Ss     0:00  \_ sshd: ubuntu [priv] 
 1501 ?        S      0:00  |   \_ sshd: ubuntu@pts/0  
11483 pts/0    Ss+    0:00  |       \_ sudo -S -p sudo password: /bin/bash -l -c /bin/bash /tmp/highstate.sh-20171213151342
11484 pts/0    S+     0:00  |           \_ /bin/bash /tmp/highstate.sh-20171213151342
11488 pts/0    S+     0:00  |               \_ sudo salt-call --force-color state.highstate -l info --retcode-passthrough
11490 pts/0    S+     0:09  |               |   \_ /usr/bin/python /usr/bin/salt-call --force-color state.highstate -l info --retcode-passt
hrough
 9233 pts/0    S+     0:00  |               |       \_ /bin/bash -c node_modules/.bin/gulp critical-css:generate ./check_critical_css.sh 
 9234 pts/0    Sl+    0:05  |               |           \_ gulp 
```

**Comment by giorgiosironi** [comment]
That shouldn't be on a single line...

**Comment by giorgiosironi** [comment]
This ran into the same problem as #37

**Comment by giorgiosironi** [comment]
Just merged the formula `master` into this and it seems it's still failing with the `Chromium unexpecedly not opened - crashed?` error on fresh stacks.

**Comment by thewilkybarkid** [comment]
*Might* fix it GitHub, slow down...

**Comment by giorgiosironi** [comment]
Good run
```
[54.172.176.183] out:           ID: generate-critical-css
[54.172.176.183] out:     Function: cmd.run
[54.172.176.183] out:         Name: node_modules/.bin/gulp critical-css:generate && ./check_critical_css.sh
[54.172.176.183] out:       Result: True
[54.172.176.183] out:      Comment: Command "node_modules/.bin/gulp critical-css:generate && ./check_critical_css.sh" run
[54.172.176.183] out:      Started: 13:20:50.919712
[54.172.176.183] out:     Duration: 28513.717 ms
[54.172.176.183] out:      Changes:   
[54.172.176.183] out:               ----------
[54.172.176.183] out:               pid:
[54.172.176.183] out:                   9922
[54.172.176.183] out:               retcode:
[54.172.176.183] out:                   0
[54.172.176.183] out:               stderr:
[54.172.176.183] out:               stdout:
[54.172.176.183] out:                   [13:20:52] Using gulpfile /srv/journal/gulpfile.js
[54.172.176.183] out:                   [13:20:52] Starting 'critical-css:clean'...
[54.172.176.183] out:                   [13:20:52] Finished 'critical-css:clean' after 7.79 ms
[54.172.176.183] out:                   [13:20:52] Starting 'critical-css:generate'...
[54.172.176.183] out:                   [13:21:19] Finished 'critical-css:generate' after 26 s
[54.172.176.183] out:                   Expected list of files in build/critical-css/:
[54.172.176.183] out:                   build/critical-css/about.css
[54.172.176.183] out:                   build/critical-css/archive-month.css
[54.172.176.183] out:                   build/critical-css/article.css
[54.172.176.183] out:                   build/critical-css/default.css
[54.172.176.183] out:                   build/critical-css/grid-listing.css
[54.172.176.183] out:                   build/critical-css/home.css
[54.172.176.183] out:                   build/critical-css/landing.css
[54.172.176.183] out:                   build/critical-css/listing.css
[54.172.176.183] out:                   build/critical-css/magazine.css
[54.172.176.183] out:                   build/critical-css/people.css
[54.172.176.183] out:                   Actual list of files in build/critical-css/:
[54.172.176.183] out:                   build/critical-css/about.css
[54.172.176.183] out:                   build/critical-css/archive-month.css
[54.172.176.183] out:                   build/critical-css/article.css
[54.172.176.183] out:                   build/critical-css/default.css
[54.172.176.183] out:                   build/critical-css/grid-listing.css
[54.172.176.183] out:                   build/critical-css/home.css
[54.172.176.183] out:                   build/critical-css/landing.css
[54.172.176.183] out:                   build/critical-css/listing.css
[54.172.176.183] out:                   build/critical-css/magazine.css
[54.172.176.183] out:                   build/critical-css/people.css
[54.172.176.183] out:                   Files generated:
[54.172.176.183] out:                   build/critical-css/about.css
[54.172.176.183] out:                   build/critical-css/archive-month.css
[54.172.176.183] out:                   build/critical-css/article.css
[54.172.176.183] out:                   build/critical-css/default.css
[54.172.176.183] out:                   build/critical-css/grid-listing.css
[54.172.176.183] out:                   build/critical-css/home.css
[54.172.176.183] out:                   build/critical-css/landing.css
[54.172.176.183] out:                   build/critical-css/listing.css
[54.172.176.183] out:                   build/critical-css/magazine.css
[54.172.176.183] out:                   build/critical-css/people.css
[54.172.176.183] out:                   Checking build/critical-css/about.css is a non-empty file...
[54.172.176.183] out:                   Checking build/critical-css/archive-month.css is a non-empty file...
[54.172.176.183] out:                   Checking build/critical-css/article.css is a non-empty file...
[54.172.176.183] out:                   Checking build/critical-css/default.css is a non-empty file...
[54.172.176.183] out:                   Checking build/critical-css/grid-listing.css is a non-empty file...
[54.172.176.183] out:                   Checking build/critical-css/home.css is a non-empty file...
[54.172.176.183] out:                   Checking build/critical-css/landing.css is a non-empty file...
[54.172.176.183] out:                   Checking build/critical-css/listing.css is a non-empty file...
[54.172.176.183] out:                   Checking build/critical-css/magazine.css is a non-empty file...
[54.172.176.183] out:                   Checking build/critical-css/people.css is a non-empty file...
```

**Pull request merged**
