### PR TITLE
Reproduce YAML quoting issue in Vagrant

### PR DESCRIPTION
**Pull request by giorgiosironi**
Follow-up https://github.com/elifesciences/builder-configuration/pull/119

On `journal.rds_articles.*.date`

### CODE REVIEW

**Comment by giorgiosironi** [comment]
@thewilkybarkid doing some experimentation here

**Comment by giorgiosironi** [comment]
Current version produces:
```
[09:53:42][elife@dev--journal:/srv/journal]$ cat parameters.yml | grep rds_articles -A 4
    example_rds_articles:
        '16846': https://repro.elifesciences.org/example.html
    
    rds_articles:
        '16846':
          date: &#39;2030-01-01T00:00:00Z&#39;
          display: https://hub.stenci.la/elife/30274/main/
          download: https://hub.stenci.la/elife/30274/files/download/article-30274.md
--
    rds_articles_manually_rendered: '16846':
  date: '2030-01-01T00:00:00Z'
  display: https://hub.stenci.la/elife/30274/main/
  download: https://hub.stenci.la/elife/30274/files/download/article-30274.md
```
The last field has broken indentation, but adding `indent` reproduces the problem with `&#39;` quoting.

**Comment by giorgiosironi** [comment]
Just removing `indent` doesn't work because the `yaml` rendered seems incredibly stupid:
```
    rds_articles:
        {'16846': {date: '2030-01-01T00:00:00Z', display: 'https://hub.stenci.la/elife/30274/main/',
    download: 'https://hub.stenci.la/elife/30274/files/download/article-30274.md'}}
```
That's an actual newline character before `download`.

**Comment by giorgiosironi** [comment]
We got to:
```
    example_rds_articles:
        {"16846": "https://repro.elifesciences.org/example.html"}
    
    rds_articles:
        {"16846": {"date": "2030-01-01T00:00:00Z", "display": "https://hub.stenci.la/elife/30274/main/", "download": "https://hub.stenci.la/elife/30274/files/download/article-30274.md"}}
    
    feature_rds:
        true
```
This is just `parameters.yml` so the production team would still edit the nicely formatted version.

**Comment by giorgiosironi** [comment]
Not particularly urgent.

**Comment by thewilkybarkid** [comment]
Urgh. The reason for trying to go for pretty YAML was for useful Salt diffs. (Embedding pretty JSON would be the same.)

Will have a little play.

**Comment by thewilkybarkid** [comment]
> The last field has broken indentation, but adding `indent` reproduces the problem with `&#39;` quoting.

Looks like we're hitting https://github.com/pallets/jinja/pull/826; assume it's using Jinja 2.10.x, fix included in 2.11.0.

**Comment by giorgiosironi** [comment]
Need to find out what Jinja is Salt using, it's probably a OS-level package rather than a virtualenv.

**Comment by giorgiosironi** [comment]
Seems 2.10 yeah:
```
[14:12:57][elife@dev--journal:/usr/lib/python2.7/dist-packages]$ ls -ld Jinja*
drwxr-xr-x 2 root root 4096 Feb 17 16:41 Jinja2-2.10.egg-info
```

**Comment by giorgiosironi** [comment]
Ah, comes from Ubuntu rather than Salt:
```
$ dpkg -l *jinja*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                      Version           Architecture      Description
+++-=========================-=================-=================-========================================================
ii  python-jinja2             2.10-1ubuntu0.18. all               small but fast and easy to use stand-alone template engi
```

**Comment by giorgiosironi** [comment]
Probably means it's not going to be updated, even 20.04 at the moment has [2.10-2ubuntu2](https://packages.ubuntu.com/focal/python-jinja2).

**Comment by thewilkybarkid** [comment]
:shakes-fist:

**Comment by thewilkybarkid** [comment]
Means for worse diffs, but better than broken configuration.

**Pull request merged**
